AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - my.service::my-service
Globals:
  Api:
    EndpointConfiguration: REGIONAL
  Function:
    Architectures:
      - arm64
    Environment:
      Variables:
        SECRET_NAME: link-shortener-saas-jwt-secret
        AWS_ACCESS_KEY_ID: fake
        AWS_SECRET_ACCESS_KEY: fake
        AWS_REGION: us-east-1
        AWS_DEFAULT_REGION: us-east-1
        SPRING_CLOUD_AWS_SECRETSMANAGER_ENDPOINT: http://localstack-main:4566
        SPRING_PROFILES_ACTIVE: local


Resources:
  MyServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: joao.StreamLambdaHandler::handleRequest
      Runtime: java21
      CodeUri: .
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        ProxyResource:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  MyServiceApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: MyServiceApi
